<?php
	/** @var Df_Qiwi_Block_Form $this */
	/**
	 * Нижеследующая стандартная для Magento разметка HTML
 	 * вместо простого echo $this->getDescription();
 	 * позволяет скрывать описание способа оплаты,
 	 * когда способ оплаты не является текущим.
	 */
	/** @var string $cssCommon */
	$cssCommon = 'input-text required-entry validate-digits validate-length ';
?>
<fieldset class='form-list'>
    <ul id='payment_form_<?php echo $this->getMethodCode(); ?>' style='display:none'>
		<li>
			<div class='input-box df-phone-container'>
				<!--
					Пока поддерживаем только российские номера,
					потому что QIWI пока не предоставляет информации
					о проводе оплаты для номеров других стран
				-->
				<div class='df-prefix'>+7</div>
				<div class='df-network-code-container'>
					<label
						for='<?php echo Df_Qiwi_Method::KEY__PHONE_NETWORK_CODE; ?>'
						class='required'
					><em>*</em>Код:</label>
					<div class='df-network-code-input-frame'>
						<div class='df-bracket df-bracket-open'>(</div>
						<input
							type='text'
							id='<?php echo Df_Qiwi_Method::KEY__PHONE_NETWORK_CODE; ?>'
							name='payment[<?php echo Df_Qiwi_Method::KEY__PHONE_NETWORK_CODE; ?>]'
							title='Код'
							class='<?php echo $cssCommon . 'df-phone-network-code minimum-length-3 maximum-length-3' ?>'
							value='<?php echo strval(substr($this->phone(), 0, 3)); ?>'
							maxlength='3'
						/>
						<div class='df-bracket df-bracket-close'>)</div>
					</div>
				</div>
				<div class='df-suffix-container'>
					<label
						for='<?php echo Df_Qiwi_Method::KEY__PHONE_SUFFIX; ?>'
						class='required'
					><em>*</em>Номер:</label>
					<input
						type='text'
						id='<?php echo Df_Qiwi_Method::KEY__PHONE_SUFFIX; ?>'
						name='payment[<?php echo Df_Qiwi_Method::KEY__PHONE_SUFFIX; ?>]'
						title='Номер'
						class='<?php echo $cssCommon . 'df-phone-suffix minimum-length-7 maximum-length-7';?>'
						value='<?php echo strval(substr($this->phone(), 3)); ?>'
						maxlength='7'
					/>
				</div>
			</div>
			<div class='df-field-comment'>
				Введите номер мобильного телефона России или Казахстана для входа в QIWI Кошелёк.
			</div>
        </li>
        <li><?php echo $this->getDescription(); ?></li>
    </ul>
</fieldset>