<?php
	/** @var Df_PageCache_Block_Debug $this */
	/** @var string $class */
	$class = get_class($this);
?>
<div style="position:relative; border:1px dotted red; margin:6px 2px; padding:18px 2px 2px 2px; zoom:1;">
    <div style="position:absolute; left:0; top:0; padding:2px 5px; background:red; color:white; font:normal 11px Arial; text-align:left !important; z-index:998;" onmouseover="this.style.zIndex='999'" onmouseout="this.style.zIndex='998'" title="<?php echo $this->getType()?>"><?php echo implode(",", $this->getTags())?></div>
    <?php echo $this->getDynamicBlockContent() ?>
</div>
