<?php /** @var Mage_Core_Block_Template $this */ ?>
<?php if ($this->getTotal()->getValue()): ?>
    <tr>
        <th colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
                <?php $_title = $this->__('Remove'); ?>
                <?php $_url = Mage::getUrl('df_customerbalance/cart/remove'); ?>
                <a href="<?php echo $_url; ?>" title="<?php echo $_title; ?>" class="btn-remove"><img src="<?php echo $this->getSkinUrl('images/btn_remove.gif') ?>" alt="<?php echo $this->__('Remove')?>" /></a>
                <?php echo $this->getTotal()->getTitle(); ?>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
        </th>
        <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
                <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
            <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
