<?php /** @var Df_Catalog_Block_Category_Navigation $this */ ?>
<!-- «Иллюстрированное меню товарных разделов» -->
<?php $numColumns = df_cfg()->catalog()->navigation()->getNumberOfColumns(); ?>
<style type='text/css'>
	.df .df-category-navigation li.df-category {width: <?php echo 98 / $numColumns; ?>%;}
</style>
<ul class='df-categories'>
	<?php
		/** @var int $ordering */
		$ordering = 0;
		foreach($this->categories() as $category) {
			/** @var Df_Catalog_Model_Category $category */
			/** @var string[] $itemClasses */
			$itemClasses = array('df-category');
			if (!($ordering % $numColumns)) {
				$itemClasses[]= 'df-break';
			}
			$ordering++;
			/** @var string $name */
			$name = df_e($category->getName());
			/** @var string $url */
			$url = df_e($category->getUrl());
			?>
				<li class='<?php echo implode(' ', $itemClasses); ?>'>
					<a href='<?php echo $url; ?>' title='<?php echo $name; ?>' class='df-image-link'>
						<img src='<?php echo $this->thumbUrl($category); ?>' alt='<?php echo $name; ?>' />
					</a>
					<a href='<?php echo $url; ?>' class='df-text-link'>
						<h2 class='df-caption'><?php echo $name; ?></h2>
					</a>
				</li>
			<?php
		}
	?>
</ul>
