<?php /** @var Mage_Adminhtml_Block_Cms_Page_Edit_Form $this */ ?>
<div class="entry-edit">
    <?php echo $this->getFormHtml() ?>
<?php /*if ( $form->getUseContainer() === true ): ?>
<form id="<?php echo $form->getFormId() ?>" method="<?php echo ( $form->getFormMethod() ) ? $form->getFormMethod() : 'post' ; ?>" action="<?php echo $form->getFormAction() ?>" <?php echo ( $form->getFormEnctype() ) ? 'enctype="' . $this->getForm()->getFormEnctype() . '"' : '' ?> >
<?php endif; ?>
    <?php foreach($form->getElements() as $_element): ?>
    <?php echo $this->drawElement($_element) ?>
    <?php endforeach; ?>
<?php if ( $form->getUseContainer() === true ): ?>
</form>
<?php endif;*/ ?>
</div>
<script type="text/javascript">
//<![CDATA[
<?php if ($this->getSelectedTabId()): ?>
Event.observe(window, 'load', function() {
    var objName = '<?php echo $this->getSelectedTabId() ?>';
    if (objName) {
        obj = $(objName);
        //IE fix(bubbling event model)
        page_tabsJsTabs.setSkipDisplayFirstTab();
        page_tabsJsTabs.showTabContent(obj);
    }
});
<?php endif; ?>
function pagePreviewAction() {
    var formElem = $('<?php echo $this->getForm()->getId()?>');
    var oldUrl = formElem.action;
    formElem.writeAttribute('target', '_blank');
    editForm.submit('<?php echo $this->getUrl('*/cms_page_revision/preview') ?>')
    formElem.writeAttribute('target', '');
    formElem.action = oldUrl;
    return true;
}
//]]>
</script>
