<?php /** @var $this Df_Banner_Block_Banner */ ?>
<?php
	if ($this->isItFirstRunForTemplate()) {
		?>
			<script 
				src='<?php echo $this->getSkinUrl('df/legacy/banner/js/legacy/galleryview/jquery.easing.1.3.js')?>' 
				type='text/javascript'
			></script>
			<script
				src='<?php echo $this->getSkinUrl('df/legacy/banner/js/legacy/galleryview/jquery.galleryview-1.1.js')?>'
				type='text/javascript'
			></script>
			<script
				src='<?php echo $this->getSkinUrl('df/legacy/banner/js/legacy/galleryview/jquery.timers-1.1.2.js')?>'
				type='text/javascript'
			></script>
		<?php
	}
	/** @var Df_Banner_Model_Banner $banner  */
	$banner = $this->getBanner();
	$delay = $banner->getDelay();
	if (!$delay) {
		$delay = 2000;
	}
	if ($banner->needShowTitle()) {
		?><h3><?php echo df_e($banner->getTitle()); ?></h3><?php
	}
	/** @var string $domId  */
	$domId =
		implode(
			'-'
			,
			array(
				'df', 'galleryview', $banner->getId()
			)
		)
	;
	df_assert_string($domId);
?>
<div id='<?php echo $domId; ?>' class='df-slideshow'>
	<?php
		$bannerItems = $this->getBannerItems();
	  	foreach($bannerItems as $bannerItem) {
			/** @var Df_Banner_Model_Banneritem $bannerItem */
			df_assert($bannerItem instanceof Df_Banner_Model_Banneritem);
			?>
				<div class='panel'>
					<a
						href='<?php echo $bannerItem->getUrl(); ?>'
					>
						<img
							src='<?php echo $this->getBannerItemImageUrl($bannerItem); ?>'
							width='<?php echo $banner->getSizeWidth().'px'?> '
							height=' <?php echo $banner->getSizeHeight().'px'?>'
							alt=''
						/>
					</a>
					<div class='panel-overlay'>
						<h2><a
							href='<?php echo $bannerItem->getUrl(); ?>'
						><?php echo $bannerItem->getTitle(); ?></a></h2>
						<p><?php echo $bannerItem->getContent(); ?></p>
					</div>
				</div>
			<?php
		}
	?>
	<ul class='filmstrip'>
		<?php
			$bannerItems = $this->getBannerItems();
		  	foreach($bannerItems as $bannerItem) {
				/** @var Df_Banner_Model_Banneritem $bannerItem */
				df_assert($bannerItem instanceof Df_Banner_Model_Banneritem);
				?>
				  	<?php if ($bannerItem->getThumbnailFileName()): ?>
						<li><img src='<?php echo df_h()->banner()->image()->init($bannerItem->getThumbnailFileName())->resize(100, 100) ?>' alt=''/></li>
						<?php elseif ($bannerItem->getThumbnailUrl()): ?>
						<li><img src='<?php echo $bannerItem->getThumbnailUrl() ?>' alt='' /></li>
						<?php elseif ($bannerItem->getImageFileName()): ?>
						<li><img src='<?php echo df_h()->banner()->image()->init($bannerItem->getImageFileName())->resize(100, 100) ?>' alt=''/></li>
					<?php endif; ?>
				<?php
			}
		?>
	</ul>
</div>
<script type='text/javascript'>
	(function($) {
		$(function() {
			$('#<?php echo $domId; ?>').galleryView({
				panel_width: <?php echo $banner->getSizeWidth(); ?>,
				panel_height: <?php echo $banner->getSizeHeight(); ?>,
				frame_width: 100,
				frame_height: 100,
				nav_theme: 'light',
				transition_interval: <?php echo $delay; ?>
			});
		});
	})(jQuery);
</script>