<?php /** @var $this Df_Banner_Block_Banner */ ?>
<?php
	if ($this->isItFirstRunForTemplate()) {
		?>
			<script
				src='<?php echo $this->getSkinUrl('df/legacy/banner/js/legacy/jquery.cycle.js')?>'
				type='text/javascript'
			></script>
		<?php
	}
	/** @var Df_Banner_Model_Banner $banner  */
	$banner = $this->getBanner();
	if ($banner->needShowTitle()) {
		?><h3><?php echo df_escape($banner->getTitle()); ?></h3><?php
	}
	/** @var string $domId  */
	$domId =
		implode(
			'-'
			,
			array(
				'df', 'simpleslider', $banner->getId()
			)
		)
	;
	df_assert_string($domId);
?>
<style type='text/css'>
	#<?php echo $domId; ?> {
		width: <?php echo $banner->getSizeWidth().'px'; ?>;
		height: <?php echo $banner->getSizeHeight().'px'; ?>;
		background: none;
		position: relative;
		display:none;
		padding: 0;
	}	
</style>
<div id='<?php echo $domId; ?>' class='df-slideshow'>
	<div class='df-slider'>
		<?php
			foreach($this->getBannerItems() as $bannerItem) {
				/** @var Df_Banner_Model_Banneritem $bannerItem */
				df_assert($bannerItem instanceof Df_Banner_Model_Banneritem);
				?>
					<a
						href='<?php echo $bannerItem->getUrl(); ?>'
					>
						<img
							src='<?php echo $this->getBannerItemImageUrl($bannerItem); ?>'
							width='<?php echo $banner->getSizeWidth().'px'?> '
							height=' <?php echo $banner->getSizeHeight().'px'?>'
							alt=''
						/>
					</a>
				<?php
			}
		?>
	</div>
	<div class='df-slider-pager'></div>
</div>
<script type='text/javascript'>
	(function($) {
		$(function() {
			$('#<?php echo $domId; ?> .df-slider').cycle({
				speed: <?php echo $banner->getDelay(); ?>,
				timeout: 3500,
				pager: '#<?php echo $domId; ?> .df-slider-pager',
				pagerEvent: 'mouseover',
				fastOnEvent: false
			});
			$('#<?php echo $domId; ?>').fadeIn(1500);
		});
	})(jQuery);
</script>
