<?php /** @var Df_Invitation_Block_Adminhtml_Invitation_View $this */ ?>
<div class="content-header">
    <?php echo $this->getHeaderHtml(); ?>
    <p class="content-buttons form-buttons">
        <?php echo $this->getButtonsHtml(); ?>
    </p>
</div>
<form id="invitation_elements" action="<?php echo $this->getSaveMessageUrl(); ?>" method="POST">
<?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
//<![CDATA[
    var invitationForm = new varienForm('invitation_elements');
//]]>
</script>
