<?php
if (false) {
	/** @var Df_MoySklad_Settings_General $s */
	$s = Df_MoySklad_Settings_General::s();
	/** @var Zend_Http_Client $c */
	$c = new Zend_Http_Client;
	$c->setUri('https://online.moysklad.ru/api/remap/1.1/entity/product');
	$c->setAuth($s->login(), $s->password());
	$c->setHeaders('content-type', 'application/json');
	$c->setRawData(json_encode(array('name' => 'Мандарины')));
	//$client->set
	/** @var Zend_Http_Response $response */
	$response = $c->request(Zend_Http_Client::POST);
	print_r(df_json_decode($response->getBody()));
}
?>
<div class='df-moysklad-export'>
	<h3 class='progress'></h3>
	<table>
		<tbody/>
	</table>
</div>
<script>(function($) {$(function() {
	/** @type {String} */
	var urlBase = '<?php echo rm_ejs(rm_url_admin('df_moysklad/export/')); ?>';
	$.getJSON(urlBase + 'products', function(products) {
		/** @type {jQuery} HTMLDivElement */
		var $c = $('.df-moysklad-export');
		/**
		 * @param {String} text
		 * @param {Object|String|Array=} params [optional]
		 */
		var log = function(text, params) {
			$c.append($('<div/>').html(rm.string.t(text, params)));
		};
		/** @type {jQuery} HTMLHeadingElement */
		var $progress = $('.progress', $c);
		/** @type {String} */
		var progressText = rm.string.t('Экспорт товара: <b>%s</b> из <b>{total}</b>', {
			total: products.length
		});
		/** @type {jQuery} HTMLTableSectionElement */
		var $tbody = $('tbody', $c);
		var process = function(i) {
			if (i < products.length) {
				var product = products[i];
				$progress.html(rm.string.t(progressText, 1 + i));
				$.getJSON(urlBase + 'product', {id: product.id}, function(status) {
					$tbody.append($(rm.string.t('<tr><td>{name}</td><td>{status}</td></tr>', {
						name: product.name, status: status
					})));
					process(++i);
				});
			}
		};
		process(0);
	})
});})(jQuery);</script>