<?php
if (false) {
	/** @var Df_MoySklad_Settings_General $s */
	$s = Df_MoySklad_Settings_General::s();
	/** @var Zend_Http_Client $c */
	$c = new Zend_Http_Client;
	$c->setUri('https://online.moysklad.ru/api/remap/1.1/entity/product');
	$c->setAuth($s->login(), $s->password());
	$c->setHeaders('content-type', 'application/json');
	$c->setRawData(json_encode(array('name' => 'Мандарины')));
	//$client->set
	/** @var Zend_Http_Response $response */
	$response = $c->request(Zend_Http_Client::POST);
	print_r(df_json_decode($response->getBody()));
}
?>
<div class='df-moysklad-export'/>
<script>(function($) {$(function() {
	jQuery.ajax({
		dataType: 'json',
		url: '<?php echo rm_ejs(rm_url_admin('df_moysklad/export/products')); ?>'
	}).done(function(products) {
		/** @type {jQuery} HTMLDivElement */
		var $container = $('.df-moysklad-export');
		/**
		 * @param {String} text
		 * @param {Object|String|Array=} params [optional]
		 */
		var log = function(text, params) {
			$container.append($('<div/>').html(rm.string.t(text, params)));
		};
		log('<h3>Товаров для экспорта: <b>%s</b></h3>', products.length);
		$.each(products, function(index, name) {
			log(name);
		});
	});
});})(jQuery);</script>