<?php /** @var Mage_Core_Block_Template $this */ ?>
<?php 
    $_order  = $this->getOrder();
    $_source = $this->getSource();
?>
<?php if ($_source->getCustomerBalanceTotalRefunded()): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo Df_CustomerBalance_Helper_Data::s()->__('Refunded to Store Credit'); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>><?php echo $_order->formatPrice($_source->getCustomerBalanceTotalRefunded()) ?></td>
</tr>
<?php endif; ?>
