<?php /** @var Df_AccessControl_Block_Admin_Tab $this */ ?>
<div class='entry-edit'>
    <div class='entry-edit-head'>
        <h4 class='icon-head head-edit-form fieldset-legend'>Доступ к товарным разделам</h4>
    </div>
    <fieldset id='role_resources'>
		<div class='field-row'>
			<label for='rm.accessControl.enable'>Настроить?</label>
			<?php echo df_html_select_yesno($this->isModuleEnabled(), array(
				'id' => 'rm.accessControl.enable'
				,'name' => 'rm.accessControl.enable'
				,'class' => 'select'
			));?>
		</div>
		<div id='rm.accessControl.settings'>
			<div class='field-row'>
				<?php echo $this->renderCategoryTree(); ?>
			</div>
		</div>
		<script type='text/javascript'>
			/** @type {Boolean} */
			var enabled = <?php echo df_bts($this->isModuleEnabled()); ?>;
			document.observe('dom:loaded', function() {
				/** @type {HTMLDivElement} */
				var settings = $('rm.accessControl.settings');
				if (!enabled) {
					settings.hide();
				}
				Event.observe('rm.accessControl.enable', 'change', function(event) {
					settings.toggle();
				});
			});
		</script>
    </fieldset>
</div>
