<?php /** @var Df_Localization_Block_Admin_Theme $this */ ?>
<div class='rm-container'>
	<div class='content-header'>
		<h1>Доступные русификаторы</h1>
	</div>
	<ul class='rm-processors'>
		<li>
			<div></div>
			<div></div>
		</li>
		<li class='rm-applicable'>
			<div>ThemeForest Infortis Fortis</div>
			<a href='javascript:void(0);'>запустить</a>
		</li>
		<li class='rm-applicable'>
			<div>EMThemes Marketplace</div>
			<a href='javascript:void(0);'>запустить</a>
		</li>
		<li class='rm-processed'>
			<div> Templates Master Argento</div>
			<div>
				<a
					href='javascript:void(0);'
					title='уже применялся 2014-09-09 18:40'
				>перезапустить</a></div>
		</li>
		<li class='rm-absent'>
			<div>ThemeForest Infortis Ultimo</div>
			<div>тема отсутствует</div>
		</li>
		<li class='rm-absent'>
			<div>ThemeForest Infortis Ultimo</div>
			<div>тема отсутствует</div>
		</li>
		<li class='rm-absent'>
			<div>ThemeForest Infortis Ultimo</div>
			<div>тема отсутствует</div>
		</li>
	</ul>
</div>

 