<?php /** @var Df_Localization_Block_Admin_Theme $this */ ?>
<div class='rm-container'>
	<div class='content-header'>
		<h1>Доступные русификаторы</h1>
	</div>
	<ul class='rm-processors'>
		<li>
			<div></div>
			<div></div>
		</li>
		<?php
			foreach (Df_Localization_Model_Onetime_Processor_Collection::s() as $processor) {
				/** @var Df_Localization_Model_Onetime_Processor $processor */
				echo $this->renderProcessor($processor);
			}
		?>
	</ul>
</div>

 