<?php /** @var Df_Checkout_Block_Frontend_Ergonomic_Address_Field_Street $this */ ?>
<?php echo $this->getLabelHtml(); ?>
<div class='input-box'>
	<input
		type='text'
		id='<?php echo $this->getDomId(); ?>'
		name='<?php echo $this->getDomName(); ?>'
		value='<?php echo df_e($this->getValue()); ?>'
		title='<?php echo $this->getLabel(); ?>'
		class='<?php echo $this->getCssClassesAsText(); ?> df-street-line-1'
	/>
</div>
<?php
	for($lineOrdering = 2; $lineOrdering <= $this->getLinesCount(); $lineOrdering++) {
		?>
<div class='input-box'>
	<input
		type='text'
		id='<?php echo $this->getDomIdForStreetLine($lineOrdering); ?>'
		name='<?php echo $this->getDomName(); ?>'
		value='<?php echo df_e($this->getValueForStreetLine($lineOrdering)); ?>'
		title='<?php echo $this->getLabel(); ?>'
		class='input-text'
	/>
</div>
		<?php
	}
?>