<?php /** @var Mage_Core_Block_Template $this */ ?>
<input type="hidden" name="creditmemo[refund_customerbalance]" value="0">
<?php if ($this->canRefundToCustomerBalance()): ?>
    <p>
        <label for="creditmemo_refund_customerbalance"><?php echo Df_CustomerBalance_Helper_Data::s()->__('Refund Store Credit to Store Credit') ?></label>
        <input type="checkbox" name="creditmemo[refund_customerbalance]" value="1" id="creditmemo_refund_customerbalance">
    </p>
<?php endif; ?>
<input type="hidden" name="creditmemo[refund_real_customerbalance]" value="0">
<?php if ($this->canRefundMoneyToCustomerBalance()): ?>
    <p>
        <label for="creditmemo_refund_real_customerbalance"><?php echo Df_CustomerBalance_Helper_Data::s()->__('Refund Money to Store Credit') ?></label>
        <input type="checkbox" name="creditmemo[refund_real_customerbalance]" value="1" id="creditmemo_refund_real_customerbalance">
    </p>
<?php endif; ?>
