<?php /** @var Df_Checkout_Block_Frontend_Ergonomic_Address_Type_Shipping $this */ ?>
<form action="" id="co-shipping-form">
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
       <li class="wide">
           <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
           <div class="input-box">
               <?php echo $this->getAddressesHtmlSelect('shipping') ?>
           </div>
       </li>
    <?php endif ?>
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            <fieldset>
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                <ul>
					<?php echo Df_Checkout_Block_Frontend_Ergonomic_Address::shipping()->toHtml(); ?>
					<li class="no-display">
						<input type="hidden" name="shipping[save_in_address_book]" value="1" />
					</li>
                </ul>
            </fieldset>
        </li>
        <li class="control">
            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if ($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
        </li>
    </ul>
    <div class="buttons-set" id="shipping-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" title="<?php echo $this->__('Continue') ?>" onclick="shipping.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shipping-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
<!-- 2017-12-19
"Magento 1.9.3.3 добавила опцию «Enable Form Key Validation On Checkout»,
которая (если её включить) ломает модуль «Удобное оформление заказа» Российской сборки Magento":
https://github.com/magento-russia/2/issues/8
-->
	<?php echo $this->getBlockHtml('formkey') ?>	
</form>
<script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
	var shippingRegionEnabled =
		<?php echo intval(
			Df_Checkout_Model_Config_Source_Field_Applicability::VALUE__NO
			!== df_cfg()->checkout()->applicabilityShipping()->region()
		); ?>
	;
	var shippingRegionUpdater =
		/**
		 * Создаём RegionUpdater только при наличии поля region,
		 * иначе будет сбой JavaScript.
		 */
			shippingRegionEnabled
			// 2015-11-16
			// Сегодня заметил, что в оформительской теме Gala SoftwareMarket
			// переменная countryRegions не инициализирована.
			&& window.countryRegions
			&& document.getElementById('shipping:country_id')
			&& document.getElementById('shipping:region')
			&& document.getElementById('shipping:region_id')
		?
			/**
			 * Однако заглушка нам всё равно нужна, ибо shippingRegionUpdater
			 * вызывается стандартным кодом.
			 */
			new RegionUpdater(
				'shipping:country_id'
				,'shipping:region'
				,'shipping:region_id'
				,countryRegions
				,undefined
				,'shipping:postcode'
			)
		: {update: function() {}}
	;
//]]>
</script>
