<?php
/**
 * 2015-04-16
 * Заменил p.note > span на div.note аналогично
 * @see Df_Adminhtml_Block_Config_Form_Field::render()
 * и app/design/adminhtml/rm/priority/template/catalog/form/renderer/fieldset/element.phtml
 * @var Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset_Element $this
 * @var Varien_Data_Form_Element_Abstract|Df_Varien_Data_Form_Element_Abstract $element
 */
$element = $this->getElement();
if (!$element->getNoDisplay()) {
	/** @var string $html */
	$html = trim($element->getElementHtml());
	/** @var string $result */
	if ('hidden' === $element->getType())  {
		$result = df_tag('td', array('colspan' => 2, 'class' => 'hidden'), $html);
	}
	else {
		/** @var array(string -> string|string[]) $css */
		$css = array('label', 'note', 'value');
		/** @noinspection PhpParamsInspection */
		$css = array_combine($css, $css);
		if ($element->getValueClass()) {
			$css['value'] = $element->getValueClass();
		}
		if ($element->getFieldsetHtmlClass()) {
			foreach ($css as &$entry) {
				$entry = array($entry, "{$element->getFieldsetHtmlClass()}-{$entry}");
			}
		}
		$result = df_tag('td', array('class' => $css['label']), trim($element->getLabelHtml()));
		if ($element->getNote()) {
			$html .= df_tag('div', array(
				'class' => $css['note']
				, 'id' => "note_{$element->getId()}"
			), $element->getNote());
		}
		$result .= df_tag('td', array('class' => $css['value']), $html);
	}
	/**
	 * 2016-05-04
	 * Раньше здесь стояло $element['html_container_id'])
	 * Это явно неправильно, потому что метод
	 * @see Varien_Data_Form_Element_Abstract::getHtmlContainerId()
	 * не является неявным, он действительно присутствует в системе,
	 * причём даже в старых версиях Magento CE:
	 * https://github.com/OpenMage/magento-mirror/blob/1.9.2.4/lib/Varien/Data/Form/Element/Abstract.php#L262-L270
	 * https://github.com/OpenMage/magento-mirror/blob/1.4.0.1/lib/Varien/Data/Form/Element/Abstract.php#L250-L258
	 * Он работает так:
		if ($this->hasData('container_id')) {
			return $this->getData('container_id');
		} elseif ($idPrefix = $this->getForm()->getFieldContainerIdPrefix()) {
			return $idPrefix . $this->getId();
		}
		return '';
	 * Поэтому $element['html_container_id']) — это явный дефект.
	 * Удивительно, что его год (2015-04-16 - 2016-05-03) никто не замечал,
	 * и только сейчас заметили: http://magento-forum.ru/topic/5422/
	 */
	echo df_tag('tr', array('id' => $element->getHtmlContainerId()), $result);
}