<?php /** @var Mage_Core_Block_Template $this */ ?>
<tr>
    <td class="label"><?php echo $this->getElement()->getLabel(); ?></td>
    <td class="value">
        <input type="text" class="input-text" style="width:125px" name="rate[value]" value="<?php echo $this->getValue(); ?>"/>
        &nbsp;&raquo;&nbsp;
        <input type="text" class="input-text" style="width:125px" name="rate[equal_value]" value="<?php echo $this->getEqualValue(); ?>"/>
    </td>
</tr>
