<?php /** @var Df_Reward_Block_Tooltip $this */ ?>
<div class="reward-message <?php echo $this->getWrapperClass()?>">
    <div class="reward">
		<?php if ($this->hasRewardMessage()):?>
			<p>
				<?php
					echo
						$this->__(
							$this->getRewardMessage()
							,
							df_h()->reward()->formatReward(
								$this->getRewardPoints()
								,
								$this->getRewardAmount()
								,
								null
								,
								'<strong>%s</strong>'
							)
						)
				?>
			</p>
		<?php endif;?>
		<?php if ($this->hasPointsBalance() && !$this->hasHideBalance()):?>
		<p class="balance">
			<?php echo $this->__('Your current balance is %s.', df_h()->reward()->formatReward($this->getPointsBalance(), null, null, '<strong>%s</strong>'))?>
		</p>
		<?php endif;?>
		<?php if (!$this->hasHideLink()):?>
			<p class="a-more"><?php echo $this->renderLearnMoreLink()?></p>
		<?php endif;?>
		<?php if ($this->hasQtyLimit() && $this->hasRewardQtyLimitationMessage()):?>
			<p class="limit"><?php echo $this->__($this->getRewardQtyLimitationMessage(), "<strong>{$this->getQtyLimit()}</strong>")?></p>
		<?php endif;?>
		<?php if ($this->hasGuestNote()):?>
			<p class="limit"><?php echo $this->__($this->getGuestNote())?></p>
		<?php endif;?>
    </div>
</div>
