<?php /** @var Mage_Core_Block_Template $this */ ?>
<?php if ($this->isAllowed()): ?>
    <div class="checkout-multishipping-payment-customerbalance" id="customerbalance_block">
        <input type="hidden" name="payment[use_customer_balance]" value="0" />
        <input type="checkbox" class="checkbox" name="payment[use_customer_balance]" value="1" id="use_customer_balance" <?php echo($this->isCustomerBalanceUsed() ? 'checked' : '') ?>/>
        <?php $balance = Mage::helper('core')->currency($this->getBalance()); ?>
        <label for="use_customer_balance"><strong><?php echo Df_CustomerBalance_Helper_Data::s()->__('Use Store Credit(%s available)', $balance); ?></strong></label>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var customerBalanceSubstracted = <?php if ($this->isCustomerBalanceUsed()): ?>true<?php else: ?>false<?php endif; ?>;
        if (customerBalanceSubstracted) {
            quoteBaseGrandTotal += <?php echo(float)df_quote()->getBaseCustomerBalanceAmountUsed(); ?>;
            customerBalanceSubstracted = false;
        }
        function switchCustomerBalanceCheckbox() {
            if (!customerBalanceSubstracted && $('use_customer_balance').checked) {
                quoteBaseGrandTotal -= <?php echo(float)$this->getBalance(); ?>;
                customerBalanceSubstracted = true;
            }
            if (customerBalanceSubstracted && !$('use_customer_balance').checked) {
                quoteBaseGrandTotal += <?php echo(float)$this->getBalance(); ?>;
                customerBalanceSubstracted = false;
            }
            if (quoteBaseGrandTotal < 0.0001) {
                var elements = Form.getElements('multishipping-billing-form');
                for(var i=0; i<elements.length; i++) {
                    if ($('use_customer_balance').checked) {
                        if (elements[i].name == 'payment[method]') {
                            elements[i].disabled = true;
                            if (elements[i].value == 'free' && elements[i].type == 'radio'){
                                elements[i].disabled = true;
                                elements[i].parentNode.hide();
                            }
                        }
                    } else {
                        if (elements[i].name=='payment[method]' && elements[i].value != 'free') {
                            elements[i].disabled = false;
                        }
                    }
                }
                if ($('use_customer_balance').checked) {
                    $('payment-methods').hide();
                    hidden = document.createElement('input');
                    hidden.type  = 'hidden';
                    hidden.name  = 'payment[method]';
                    hidden.value = 'free';
                    hidden.id    = 'customerbalance_hidden_payment';
                    $('customerbalance_block').appendChild(hidden);
                } else {
                    if ($('customerbalance_hidden_payment')) {
                        $('customerbalance_block').removeChild($('customerbalance_hidden_payment'));
                    }
                    $('payment-methods').show();
                }
            } else {
                var elements = Form.getElements('multishipping-billing-form');
                for(var i=0; i<elements.length; i++) {
                    if (elements[i].name=='payment[method]' && elements[i].value != 'free') {
                        elements[i].disabled = false;
                    }
                }
                $('payment-methods').show();
            }
        }
        Event.observe($('use_customer_balance'), 'change', switchCustomerBalanceCheckbox);
        Event.observe(window, 'load', switchCustomerBalanceCheckbox);
        function setUseCustomerBalanceEnabled() {
            $('use_customer_balance').disabled = false;
        }
        Event.observe(window, 'load', setUseCustomerBalanceEnabled);
    //]]>
    </script>
<?php endif; ?>
