<?php /** @var Mage_Checkout_Block_Onepage_Success $this */ ?>
<div class="page-title">
    <h1 style='color:#00B050;'>Оплата прошла успешно.</h1>
</div>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
