<?php /** @var Df_Admin_Block_System_Config_Form_Field_Button_Action $this */ ?>
<?php
	/** @var string $caption */
	$caption = df_escape($this->getData(Df_Admin_Block_System_Config_Form_Field_Button_Action::P__CAPTION));
	/** @var string $htmlId */
	$htmlId = $this->getData(Df_Admin_Block_System_Config_Form_Field_Button_Action::P__HTML_ID);
	/** @var string $url */
	$url = $this->getData(Df_Admin_Block_System_Config_Form_Field_Button_Action::P__URL);
?>
<button
	type='button'
	class='rm-action'
	id='<?php echo $htmlId; ?>'><?php echo $caption; ?>
</button>
<script type='text/javascript'>
	(function($){$(function() {
		/** @type string */
		var elementId = '<?php echo $htmlId; ?>';
		/** @type string */
		var url = '<?php echo $url; ?>';
		/** @type {jQuery} HTMLButtonElement */
		var $element = $('#' +  elementId);
		$element.click(
			function() {
				window.open(url, '_blank');
			}
		);
	});})(jQuery);
</script>