<?php /** @var Mage_Core_Block_Template $this */ ?>
<?php if ($data = $this->getRevisions()): ?>
<label for="revision_switcher"><?php echo $this->__('Choose Revision') ?>:</label>
<select name="revision_switcher" id="revision_switcher">
    <option value=""><?php echo $this->__('Current Modification') ?></option>
    <?php foreach($data as $row): ?>
        <optgroup label="<?php echo $row['label'] ?>">
        <?php foreach($row['revisions'] as $item): ?>
            <option value="<?php echo $item->getId() ?>"<?php if ($this->getRevisionId() == $item->getId()): ?> selected="selected"<?php endif; ?>>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->__('Revision #%s', $item->getRevisionNumber()) ?></option>
        <?php endforeach; ?>
    <?php endforeach; ?>
</select>
<script type="text/javascript">
//<![CDATA[
Event.observe($('revision_switcher'), 'change', function(event) {
    var element = Event.element(event);
    $('preview_selected_revision').value = element.value;
    togglePublish(element.value);
});
//]]>
</script>
<?php endif; ?>
