<?php /** @var \Df\Pd4\Block\LinkToDocument\ForLastOrder $this */ ?>
<div class='df'>
	<div class='df-pd4'>
		<div class='df-order-info'>
			Мы подготовили для Вас уже заполненную
			<a
				title='Распечатать платёжную форму ПД-4'
				target='_blank'
				href='<?php echo $this->getPaymentDocumentUrl(); ?>'
			>платёжную форму ПД-4</a>.
			<br/>Вам осталось её распечатать и оплатить Ваш заказ в банке!
		</div>
	</div>
</div>
